-- Rehearsal Planner — canonical database schema
--
-- This file defines the target state of the database.
-- Use it to create a database from scratch (via init_db.py).
--
-- To update an EXISTING database, run: python migrate.py
-- Do not edit this file to add incremental changes — write a new migration
-- file in migrations/ instead, then update this file to match.
--
-- Neon Auth (Better Auth) manages neon_auth."user" automatically.
-- Note: "user" is a SQL reserved word — always quote it.

-- ── Migration tracking ────────────────────────────────────────────────────────
-- Records which migration files have been applied to this database.

CREATE TABLE IF NOT EXISTS schema_migrations (
    filename   TEXT        PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Band / Collaboration ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS bands (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT        NOT NULL,
    invite_token    TEXT        UNIQUE NOT NULL DEFAULT gen_random_uuid()::text,
    -- Per-member average rating (1–5 Likert) required to approve a song.
    -- threshold = ceil(band_size * approval_factor). Default 3.25.
    -- At 3.25: 4 Mehs (12) and 2 Love+2 Hard-no (12) both fall below the 13-pt threshold.
    approval_factor NUMERIC     NOT NULL DEFAULT 3.25,
    -- Default timing settings seeded into new setlists for this band.
    default_target_seconds        INTEGER NOT NULL DEFAULT 9000,
    default_warn_seconds          INTEGER NOT NULL DEFAULT 7200,
    default_song_buffer_seconds   INTEGER NOT NULL DEFAULT 45,
    default_tuning_change_seconds INTEGER NOT NULL DEFAULT 60,
    default_break_count           INTEGER NOT NULL DEFAULT 0,
    default_break_seconds         INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Many-to-many: a user can belong to multiple bands; a band has multiple members.
CREATE TABLE IF NOT EXISTS band_members (
    band_id   UUID NOT NULL REFERENCES bands(id)            ON DELETE CASCADE,
    user_id   UUID NOT NULL REFERENCES neon_auth."user"(id) ON DELETE CASCADE,
    role      TEXT NOT NULL DEFAULT 'member',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (band_id, user_id)
);

-- ── Songs ─────────────────────────────────────────────────────────────────────
-- A song belongs to either a band (shared library) or a user (personal library).
-- Exactly one of band_id / user_id must be set — enforced by the CHECK constraint.
--
-- external_id: the Spotify track ID for Spotify-sourced songs, or a generated
-- ID for songs added before this model. NULL for fully custom songs.
--
-- added_by: which user originally added this song to the library.

CREATE TABLE IF NOT EXISTS songs (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    external_id     TEXT,
    band_id         UUID        REFERENCES bands(id)             ON DELETE CASCADE,
    user_id         UUID        REFERENCES neon_auth."user"(id)  ON DELETE CASCADE,
    added_by        UUID        REFERENCES neon_auth."user"(id)  ON DELETE SET NULL,
    name            TEXT        NOT NULL,
    artist          TEXT        NOT NULL DEFAULT '',
    duration_raw    TEXT        NOT NULL DEFAULT '',
    duration_sec    INTEGER     NOT NULL DEFAULT 0,
    status          TEXT        NOT NULL DEFAULT 'For Consideration',
    tuning          TEXT,
    recorded_tuning TEXT,
    our_tuning      TEXT,
    album_art       TEXT,
    spotify_url     TEXT,
    youtube_link    TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT song_has_one_owner CHECK (
        (band_id IS NOT NULL AND user_id IS NULL) OR
        (band_id IS NULL     AND user_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS songs_user_idx        ON songs (user_id);
CREATE INDEX IF NOT EXISTS songs_band_idx        ON songs (band_id);
CREATE INDEX IF NOT EXISTS songs_external_id_idx ON songs (external_id);

-- Duplicate guards: the same external song appears at most once per library.
-- Partial unique indexes — enforced only when both an owner and an external_id
-- exist, so different bands can each hold the same song, and fully custom songs
-- (external_id NULL) are never auto-deduplicated.
CREATE UNIQUE INDEX IF NOT EXISTS songs_band_external_uniq
    ON songs (band_id, external_id)
    WHERE band_id IS NOT NULL AND external_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS songs_user_external_uniq
    ON songs (user_id, external_id)
    WHERE user_id IS NOT NULL AND external_id IS NOT NULL;

-- ── Setlists ──────────────────────────────────────────────────────────────────
-- A named, ordered list of songs. Belongs to either a band or a user.
-- Multiple setlists per band or user are supported.

CREATE TABLE IF NOT EXISTS setlists (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name       TEXT        NOT NULL DEFAULT 'Main Set',
    band_id    UUID        REFERENCES bands(id)             ON DELETE CASCADE,
    user_id    UUID        REFERENCES neon_auth."user"(id)  ON DELETE CASCADE,
    -- Per-setlist timing settings (copy-on-create from band defaults; source of truth).
    target_seconds        INTEGER NOT NULL DEFAULT 9000,
    warn_seconds          INTEGER NOT NULL DEFAULT 7200,
    song_buffer_seconds   INTEGER NOT NULL DEFAULT 45,
    tuning_change_seconds INTEGER NOT NULL DEFAULT 60,
    break_count           INTEGER NOT NULL DEFAULT 0,
    break_seconds         INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT setlist_has_one_owner CHECK (
        (band_id IS NOT NULL AND user_id IS NULL) OR
        (band_id IS NULL     AND user_id IS NOT NULL)
    )
);

-- Ordered songs within a setlist.
-- plays = how many times this song is performed in this particular set.
CREATE TABLE IF NOT EXISTS setlist_songs (
    setlist_id UUID    NOT NULL REFERENCES setlists(id) ON DELETE CASCADE,
    song_id    UUID    NOT NULL REFERENCES songs(id)    ON DELETE CASCADE,
    position   INTEGER NOT NULL,
    plays      INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (setlist_id, song_id)
);

CREATE INDEX IF NOT EXISTS setlist_songs_position_idx ON setlist_songs (setlist_id, position);

-- ── Song Proposals & Voting ───────────────────────────────────────────────────
-- Proposals allow band members to vote on whether a song joins the shared library.

CREATE TABLE IF NOT EXISTS song_proposals (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    band_id     UUID        NOT NULL REFERENCES bands(id)   ON DELETE CASCADE,
    song_id     UUID        NOT NULL REFERENCES songs(id)   ON DELETE CASCADE,
    proposed_by UUID        REFERENCES neon_auth."user"(id) ON DELETE SET NULL,
    status      TEXT        NOT NULL DEFAULT 'pending',
    score       INTEGER     NOT NULL DEFAULT 2,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS song_votes (
    proposal_id UUID NOT NULL REFERENCES song_proposals(id) ON DELETE CASCADE,
    user_id     UUID NOT NULL REFERENCES neon_auth."user"(id) ON DELETE CASCADE,
    vote        TEXT NOT NULL,
    reason      TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (proposal_id, user_id)
);

-- ── Notifications ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS notifications (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL REFERENCES neon_auth."user"(id) ON DELETE CASCADE,
    proposal_id UUID        REFERENCES song_proposals(id) ON DELETE CASCADE,
    type        TEXT        NOT NULL DEFAULT 'new_proposal',
    details     JSONB,
    read        BOOLEAN     NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── User-added tunings ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS user_tunings (
    user_id UUID NOT NULL REFERENCES neon_auth."user"(id) ON DELETE CASCADE,
    tuning  TEXT NOT NULL,
    PRIMARY KEY (user_id, tuning)
);

-- ── User Profile & Preferences ────────────────────────────────────────────────
-- Neon Auth (Better Auth) owns neon_auth."user"; app-side identity/prefs live here.

CREATE TABLE IF NOT EXISTS user_profiles (
    user_id      UUID PRIMARY KEY REFERENCES neon_auth."user"(id) ON DELETE CASCADE,
    display_name TEXT,
    roles        TEXT[]      NOT NULL DEFAULT '{}',
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Per-user notification toggles. A missing row means all notifications are on
-- (handled in queries via COALESCE — no backfill needed).
CREATE TABLE IF NOT EXISTS notification_prefs (
    user_id         UUID PRIMARY KEY REFERENCES neon_auth."user"(id) ON DELETE CASCADE,
    new_proposal    BOOLEAN NOT NULL DEFAULT true,
    proposal_failed BOOLEAN NOT NULL DEFAULT true,
    song_archived   BOOLEAN NOT NULL DEFAULT true
);
